//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flummery.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastBrowsedFolder {
            get {
                return ((string)(this["LastBrowsedFolder"]));
            }
            set {
                this["LastBrowsedFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathCarmageddonReincarnation {
            get {
                return ((string)(this["PathCarmageddonReincarnation"]));
            }
            set {
                this["PathCarmageddonReincarnation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathCarmageddon2 {
            get {
                return ((string)(this["PathCarmageddon2"]));
            }
            set {
                this["PathCarmageddon2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveAsLevelPath {
            get {
                return ((string)(this["SaveAsLevelPath"]));
            }
            set {
                this["SaveAsLevelPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveAsVehiclePath {
            get {
                return ((string)(this["SaveAsVehiclePath"]));
            }
            set {
                this["SaveAsVehiclePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathCarmageddon1 {
            get {
                return ((string)(this["PathCarmageddon1"]));
            }
            set {
                this["PathCarmageddon1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("V")]
        public char KeysCameraSelect {
            get {
                return ((char)(this["KeysCameraSelect"]));
            }
            set {
                this["KeysCameraSelect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X")]
        public char KeysCameraPan {
            get {
                return ((char)(this["KeysCameraPan"]));
            }
            set {
                this["KeysCameraPan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Z")]
        public char KeysCameraZoom {
            get {
                return ((char)(this["KeysCameraZoom"]));
            }
            set {
                this["KeysCameraZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public char KeysCameraRotate {
            get {
                return ((char)(this["KeysCameraRotate"]));
            }
            set {
                this["KeysCameraRotate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("F")]
        public char KeysCameraFrame {
            get {
                return ((char)(this["KeysCameraFrame"]));
            }
            set {
                this["KeysCameraFrame"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForUpdates {
            get {
                return ((bool)(this["CheckForUpdates"]));
            }
            set {
                this["CheckForUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public char KeysActionScaleUp {
            get {
                return ((char)(this["KeysActionScaleUp"]));
            }
            set {
                this["KeysActionScaleUp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/")]
        public char KeysActionScaleDown {
            get {
                return ((char)(this["KeysActionScaleDown"]));
            }
            set {
                this["KeysActionScaleDown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D")]
        public char KeysClearSelection {
            get {
                return ((char)(this["KeysClearSelection"]));
            }
            set {
                this["KeysClearSelection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("W")]
        public char KeysRenderMode {
            get {
                return ((char)(this["KeysRenderMode"]));
            }
            set {
                this["KeysRenderMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public char KeysCoordinateSystem {
            get {
                return ((char)(this["KeysCoordinateSystem"]));
            }
            set {
                this["KeysCoordinateSystem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PersonalAuthor {
            get {
                return ((string)(this["PersonalAuthor"]));
            }
            set {
                this["PersonalAuthor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PersonalWebsite {
            get {
                return ((string)(this["PersonalWebsite"]));
            }
            set {
                this["PersonalWebsite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseFlummeryWorkingDirectory {
            get {
                return ((bool)(this["UseFlummeryWorkingDirectory"]));
            }
            set {
                this["UseFlummeryWorkingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PathCarmageddonMaxDamage {
            get {
                return ((string)(this["PathCarmageddonMaxDamage"]));
            }
            set {
                this["PathCarmageddonMaxDamage"] = value;
            }
        }
    }
}
